### ISSUE TITLE
gateway网关，web服务是考虑的哪些业务上的不同。

### ISSUE THREAD

**Issue by JianjianMeng** [BixinTech/sona#11]
为什么创建房间业务不走gateway网关，走web服务。

**Comment by daqingllm** [comment]
你好，SONA提供的gateway网关是一个支持自定义TCP、Websocket的长连接协议的服务，以维护在房状态和收发消息为主要目的，并不是一般意义上的通用网关服务，不支持如http等短链接协议。类似创建房间这类强业务逻辑接口，由短链接协议的web服务来支持更适合。由于SONA是一个音视频房间基建解决方案，设计上本身就考虑到充分支持业务的定制化需求，因此提供了比较丰富的业务扩展能力。在比心，SONA的web服务这一层，实际也是通过比心自研的统一网关服务对外暴露的。
