### ISSUE TITLE
DDD在SONA中的应用

### ISSUE THREAD

**Issue by JianjianMeng** [BixinTech/sona#12]
最近在调研DDD领域模型设计；希望在使用SONA的过程中DDD作为项目架构的指导依据。
分析发现SONA项目中也有使用了DDD思想。尤其是发现项目中有domain结构，其中有定义房间的要素和一些基本行为。
1.SONA设计开发过程中是否使用了DDD?
2.如果是能简单介绍下SONA的领域模型或抽象模型时的关注点。

**Comment by daqingllm** [comment]
你好，SONA在实现时没有严格按照DDD的方式落地，不过我可以大致介绍下SONA设计中的区别。
DDD中以聚合根的形式封装了业务逻辑方法，对应的实体为充血模型。而SONA中domain包下的类是以数据结构和数据类转换的工具为主，是失血模型，理念有所不同，只是恰巧用了domain这个名字。
SONA的设计是以功能划分模块的形式组织，而模块内部是通过传统的分层架构方式来实现的，以sona-service为例，房间管理(room)、房间消息(im)分属不同模块，以最外层包路径来区分，开发者可以方便地将两个模块移植到不同的服务上分别部署。模块内部的分层结构为：controller（服务接口层） -> manager（服务实现层） -> service（通用逻辑层） -> mapper（数据层）；每层之间只能单向依赖，同一层级尽量避免直接依赖，一个mapper只能被一个service所引用，controller或manager不能引用mapper；service作为最基础的功能封装，承担了实现高并发、数据一致性等非功能需求的职责。
由于SONA并不是一个很庞大的业务系统，并不包含非常复杂的业务逻辑或扩展要求，选择用DDD的方式设计并不能带来很大的收益。而采用分层架构设计可以更专注于服务的高性能优化，对于SONA作为音视频房间解决方案的基础服务的定位更加适合。
